### ISSUE TITLE
Vacation Page - Status dropdown

### ISSUE THREAD

**Issue by CrystallDEV** [micromata/projectforge#117]
The status dropdown gives you multiple options while creating a new vacation request. These options are still selectable even if you are missing the permissions to select one of those options. This could be improved by either removing the dropdown completely and set the default option "In Abstimmung" or by removing the dropdown options that are not selectable by the current user.
![image](https://user-images.githubusercontent.com/16579555/79431447-c1d05a00-7fca-11ea-904f-ebda066488f4.png)
![image](https://user-images.githubusercontent.com/16579555/79431479-ceed4900-7fca-11ea-9e5c-6e1b0583dfb5.png)

**Comment by kreinhard** [comment]
Done
