### ISSUE TITLE
Customer ReactSelect or ObjectSelect?

### ISSUE THREAD

**Issue by finreinhard** [micromata/projectforge#122]

**Comment by kreinhard** [comment]
Editing one customer and selecting "Buchungskonto" doesn't work (the chosen entry of the autocompletion drop down choice isn't displayed), but it will be saved correctly.

**Comment by kreinhard** [comment]
This bug sucks also for editing addresses (address books) as well as for editing calendars (users and groups).

**Comment by kreinhard** [comment]
Should be obsolete with release 8.1
