### ISSUE TITLE
New Chrome version results in annoying translations

### ISSUE THREAD

**Issue by kreinhard** [micromata/projectforge#148]
Nach den letzten Chrome-Updates schlägt der Browser immer automatisch vor, die Seite von EN nach DE zu übersetzen. Das ist recht nervig und wenn man dann versehentlich den Auto-Übersetzer scharf hat, kann das zu uncoolen Übersetzungseffekten führen  

Das Problem hatten wir auch im CONF ... weil im ganz ursprünglichen HTML-Quelltext das lang-Attribut mit EN gesetzt war. Den lang-Attribut haben wir einfach entfernt. Das wird dann ja dynamisch erzeugt. Das würde ich auch für PF empfehlen.

**Comment by finreinhard** [comment]
92be09651859cfb987bc672bdefde9897a27cf64
