### ISSUE TITLE
Could not run projectforge-application-6.26.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by tawfikm** [micromata/projectforge#22]
Hello team projectForge,

I'm using Win8 and I want to test the Software features but I couldn't execute the .jar file in my computer, I got this Error:
 ----------------------------------------------------------------------------------------------------------org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.137 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.EingangsrechnungDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.152 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.framework.pe
rsistence.user.entities.UserPrefDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of th
read:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.152 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.tea
mcal.event.model.TeamEventAttendeeDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of
thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.152 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.tea
mcal.event.model.TeamEventDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.168 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.RechnungsPositionDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.168 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.EingangsrechnungsPositionDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.168 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.hum
anresources.HRPlanningEntryDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.183 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.add
ress.AddressDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.183 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.kost.Kost2ArtDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.183 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.EmployeeTimedDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.183 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.framework.pe
rsistence.user.entities.TenantDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thre
ad:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.199 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.scr
ipting.ScriptDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.199 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.framework.pe
rsistence.history.entities.PfHistoryMasterDO] but has failed to stop it. This is very likely to create a memory leak. Stack t
race of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.199 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.tas
k.TaskDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.215 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.framework.ac
cess.AccessEntryDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.215 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.RechnungDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.215 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.tea
mcal.event.model.TeamEventAttachmentDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace o
f thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.230 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.KundeDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.230 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.EmployeeSalaryDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.230 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.org
a.PostausgangDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.246 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.org
a.VisitorbookDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.246 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.tea
mcal.admin.model.TeamCalDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.246 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.EmployeeDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.262 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.add
ress.AddressbookDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.262 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.hum
anresources.HRPlanningDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.262 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.framework.pe
rsistence.user.entities.UserRightDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of t
hread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.277 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Hibernate Search sync consumer thread for index org.projectforge.business.fib
u.kost.KostZuweisungDO] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.parkCurrentThread(SyncWorkProcessor.java:168)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor.access$300(SyncWorkProcessor.java:35)
 org.hibernate.search.backend.impl.lucene.SyncWorkProcessor$Consumer.run(SyncWorkProcessor.java:143)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.277 user:  WARN 9764 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application
 [ROOT] appears to have started a thread named [Wicket-PageSavingThread] but has failed to stop it. This is very likely to cr
eate a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
 java.util.concurrent.LinkedBlockingQueue.poll(Unknown Source)
 org.apache.wicket.pageStore.AsynchronousDataStore$PageSavingRunnable.run(AsynchronousDataStore.java:345)
 java.lang.Thread.run(Unknown Source)
2019-06-12 12:35:48.293 user:  INFO 9764 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-06-12 12:35:48.308 user: ERROR 9764 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may b
e misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this applicat
ion to listen on another port.

2019-06-12 12:35:48.324 user:  INFO 9764 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down Execu
torService 'taskScheduler'
2019-06-12 12:35:48.324 user:  INFO 9764 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down Execu
torService 'applicationTaskExecutor'
2019-06-12 12:35:48.340 user:  INFO 9764 --- [           main] o.p.b.user.UserXmlPreferencesCache       : Syncing all user pr
eferences to database.
2019-06-12 12:35:48.340 user:  INFO 9764 --- [           main] o.p.b.user.UserXmlPreferencesCache       : Flushing all user p
references to data-base....
2019-06-12 12:35:48.340 user:  INFO 9764 --- [           main] o.p.b.user.UserXmlPreferencesCache       : Flushing of user pr
eferences to data-base done.
2019-06-12 12:35:48.402 user:  INFO 9764 --- [           main] o.s.b.f.support.DisposableBeanAdapter    : Destroy method 'clo
se' on bean with name 'entityManagerFactory' threw an exception: java.lang.IllegalStateException: EntityManagerFactory is clo
sed
2019-06-12 12:35:48.402 user:  INFO 9764 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shut
down initiated...
2019-06-12 12:35:48.402 user:  INFO 9764 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shut
down completed.

C:\Users\elitebook\Downloads>

**Comment by kreinhard** [comment]
You use a snapshot which isn't stable in any case because it's work in progress. We're working on version 7 and it will take some weeks. Stay tuned.

Please note this as part of your error messages: The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use.

**Comment by kreinhard** [comment]
I tested it, I can reproduce your error with the snapshot jar, if I try to start ProjectForge twice.

**Comment by tawfikm** [comment]
Thanks @kreinhard, I tested "projectforge-application-6.25.0.jar" and it's working now, I think my problem was related to the port choice(8080) which was already in use ...
