### ISSUE TITLE
Adding my own Plugins

### ISSUE THREAD

**Issue by tawfikm** [micromata/projectforge#23]
Hello team ProjectForge,

Please how can I add my own plugins to your project? do you provide any API?

Thanks

**Comment by kreinhard** [comment]
Hi, for version 6.x there are example plugins. Currently we're working on version 7.x with a full functioning REST-API for all entities in ProjectForge (all CRUD-operations and much more will be provided).
So, I suggest to stay tuned and to come back in a couple of weeks after launching 7.x
Kind regards
Kai

**Comment by kreinhard** [comment]
Version 7 supports now plugins, refer the docs.
