### ISSUE TITLE
Boolean values in Magicfilter

### ISSUE THREAD

**Issue by kreinhard** [micromata/projectforge#33]
Should be realized through checkbox, see deleted field in list page.

- [ ] short description, like tooltip
- [x] change label
- [ ] future: add deleteOnFalse, now always set to true

**Comment by finreinhard** [comment]
We should add a short description and change the label from "deleted: true" to something like "show deleted".

**Comment by finreinhard** [comment]
Add deleteOnFalse

**Comment by finreinhard** [comment]
add tooltip

**Comment by finreinhard** [comment]
default value should be true

**Comment by kreinhard** [comment]
Should be obsolete with new release 8.1
