### ISSUE TITLE
DatePicker: format and show current date in calendar

### ISSUE THREAD

**Issue by kreinhard** [micromata/projectforge#48]
Date format should be the user's date format and the popup calendar should show the current date value of the text field.

**Comment by finreinhard** [comment]
![Screenshot 2020-02-21 at 11 59 25 AM](https://user-images.githubusercontent.com/13620998/75029040-a7ce3b80-54a1-11ea-8dfe-fc5b063d95b4.png)
Translations needed

**Comment by finreinhard** [comment]
wip: https://github.com/micromata/projectforge/tree/fix/48-data-picker

**Comment by finreinhard** [comment]
- [ ] translations for modifiedInterval on ListPage
- [ ] timesheets customized time intervall

**Comment by finreinhard** [comment]
- [ ] today translation
- [ ] datetimerange localization

**Comment by finreinhard** [comment]
- [ ] Edit Page Validation
