### ISSUE TITLE
switch database to mysql

### ISSUE THREAD

**Issue by joewee** [micromata/projectforge#6]
Hi 
  I have  trouble when switch the database hsqldb to mysql  as follow: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
can you tell me how to switch the database to mysql ，thanks a lot！

**Comment by FlowsenAusMonotown** [comment]
Hi,
we normally use postgres as database provider. We have to check first, what is the problem with mysql. I will review it and give you soon feedback.
Best regards, Florian

**Comment by FlowsenAusMonotown** [comment]
Hi,
unfortunately we cannot support mysql because of the restricted column and row length of mysql. The changes would have to much effort to support it. Please use postgres database for runnig projectforge.
Best regards,
Florian
