### ISSUE TITLE
Allow tooltips in UIReadOnlyField

### ISSUE THREAD

**Issue by kreinhard** [micromata/projectforge#91]
Error: The target 'davToken' could not be identified in the dom, tip: check spelling
loadFormPage/</<
src/actions/form.js:93

  90 |     )
  91 |         .then(handleHTTPErrors)
  92 |         .then(response => response.json())
> 93 |         .then(json => dispatch(callSuccess(category, Object.combine(params, json))))
  94 |         .catch(error => callFailure(category, error));
  95 | };
  96 |

**Comment by finreinhard** [comment]
fixed in page size branch
